{
  "type": "ess-scenario/4",
  "domain": "mantle.launch",
  "scenario": "bad-environment-name",
  "summary": "bad-environment-name",
  "timeline": [
    {
      "at": "2026-10-02T00:00:00Z",
      "command": "mantle.launch.ParseArgs",
      "input": {
        "argv": [
          "c2VydmU=",
          "LS1kaXI=",
          "L3Nlc3Npb24=",
          "LS1jd2Q=",
          "L3dvcmtzcGFjZQ==",
          "LS1zZWNyZXQtZmQ=",
          "Mw==",
          "LS1zZWNyZXQtZW52",
          "QkFEPU5BTUU=",
          "LS0=",
          "L2FnZW50"
        ]
      },
      "outcome": "returned",
      "response": {
        "accepted": false,
        "serve": null,
        "attach": null
      }
    }
  ]
}
