//! Deterministic complete notices from the locked graph plus actual composite/runtime grants.
use crate::{command, text};
use anyhow::{Context, Result, ensure};
use mantle_artifact::{read_bounded, sha256};
use serde_json::Value;
use std::{collections::BTreeMap, fs, path::Path, process::Command};
const SIMD_SHA: &str = "71674605ec4c087fe9eb534e3e4f9e26eb2e4aabcd76a29fd156c6a844d44b3d";
const SIMD: &str = include_str!("../licenses/simd-d74c030-LICENSE");
const MUSL: &str = include_str!("../licenses/musl-1.2.5-COPYRIGHT");
const MUSL_SHA: &str = "f9bc4423732350eb0b3f7ed7e91d530298476f8fec0c6c427a1c04ade22655af";
fn escape(value: &str) -> String {
    value
        .replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
}
fn section(html: &mut String, title: &str, body: &str) {
    html.push_str(&format!(
        "<h2>{}</h2>\n<pre>{}</pre>\n",
        escape(title),
        escape(body)
    ));
}
pub fn generate(source: &Path, check: bool) -> Result<()> {
    ensure!(
        text(Command::new("cargo-about").arg("--version"))? == "cargo-about 0.9.1",
        "cargo-about 0.9.1 required"
    );
    let output = command(
        Command::new("cargo-about").current_dir(source).args([
            "generate",
            "--workspace",
            "--locked",
            "--offline",
            "--fail",
            "--target",
            mantle_artifact::GNU,
            "--target",
            mantle_artifact::MUSL,
            "--format",
            "json",
        ]),
        300,
        32 * 1024 * 1024,
    )?;
    let value: Value = serde_json::from_slice(&output)?;
    let licenses = value["licenses"]
        .as_array()
        .context("cargo-about licenses")?;
    let mut ordered = BTreeMap::new();
    let mut packages = BTreeMap::new();
    for license in licenses {
        let body = license["text"]
            .as_str()
            .context("license text")?
            .replace("\r\n", "\n");
        let mut names = Vec::new();
        for used in license["used_by"].as_array().context("license users")? {
            let package = &used["crate"];
            let name = package["name"].as_str().context("crate name")?;
            let version = package["version"].as_str().context("crate version")?;
            let identity = format!("{name} {version}");
            names.push(identity.clone());
            packages.insert(
                identity,
                (
                    name.to_owned(),
                    version.to_owned(),
                    std::path::PathBuf::from(
                        package["manifest_path"].as_str().context("crate path")?,
                    ),
                ),
            );
        }
        names.sort();
        let title = format!(
            "{} — {}",
            license["name"].as_str().context("license name")?,
            names.join(", ")
        );
        ordered.insert(title, body);
    }
    let mut html = String::from(
        "<!doctype html>\n<html lang=\"en\"><meta charset=\"utf-8\"><title>Mantle third-party notices</title><body>\n<h1>Mantle third-party notices</h1>\n<p>Generated by mantle-release and cargo-about 0.9.1 for the locked workspace graph on x86_64 Linux GNU and musl. Mantle is Apache-2.0; see LICENSE. Distributed runtime notices accompany each bundle separately.</p>\n",
    );
    for (title, body) in ordered {
        section(&mut html, &title, &body);
    }
    for (identity, (name, version, manifest)) in packages {
        let dir = manifest.parent().context("crate directory")?;
        let mut paths = BTreeMap::new();
        for entry in fs::read_dir(dir)? {
            let entry = entry?;
            let name = entry.file_name().to_string_lossy().to_string();
            if name.starts_with("NOTICE") && entry.file_type()?.is_file() {
                paths.insert(name, entry.path());
            }
        }
        if name == "aws-lc-sys" {
            paths.insert("LICENSE".into(), dir.join("LICENSE"));
            paths.insert("aws-lc/LICENSE".into(), dir.join("aws-lc/LICENSE"));
        }
        if name == "ring" {
            for file in ["LICENSE", "LICENSE-BoringSSL", "LICENSE-other-bits"] {
                paths.insert(file.into(), dir.join(file));
            }
        }
        for (name, path) in paths {
            section(
                &mut html,
                &format!("{identity}: complete {name}"),
                &String::from_utf8(read_bounded(&path, 2 * 1024 * 1024)?)?.replace("\r\n", "\n"),
            );
        }
        if name == "base64-simd" || name == "vsimd" {
            ensure!(
                version == "0.8.0" && sha256(SIMD.as_bytes()) == SIMD_SHA,
                "unrecognized SIMD license provenance"
            );
            section(
                &mut html,
                &format!(
                    "{identity}: upstream MIT grant; Nugine/simd commit d74c030d9dc4f3cae02146d1f497ff62726ef09a; SHA256 {SIMD_SHA}"
                ),
                SIMD,
            );
        }
    }
    html.push_str("</body></html>\n");
    let path = source.join("THIRD_PARTY_LICENSES.html");
    if check {
        ensure!(
            fs::read(path)? == html.as_bytes(),
            "THIRD_PARTY_LICENSES.html differs from the locked notice generator"
        );
    } else {
        fs::write(path, html)?;
    }
    Ok(())
}
/// Identify the actual bundled target runtime before attaching its notice.
pub fn runtime_notices() -> Result<(Vec<u8>, Vec<u8>)> {
    let sysroot = text(Command::new("rustc").args(["--print", "sysroot"]))?;
    let root = Path::new(&sysroot);
    let copyright = read_bounded(
        &root.join("share/doc/rust/COPYRIGHT-library.html"),
        4 * 1024 * 1024,
    )?;
    let archive = root.join("lib/rustlib/x86_64-unknown-linux-musl/lib/self-contained/libc.a");
    let version = command(
        Command::new("ar").arg("p").arg(archive).arg("version.lo"),
        30,
        1024 * 1024,
    )?;
    ensure!(
        version.windows(6).any(|b| b == b"1.2.5\0") && sha256(MUSL.as_bytes()) == MUSL_SHA,
        "unrecognized musl runtime provenance"
    );
    Ok((copyright, MUSL.as_bytes().to_vec()))
}
